export const Routes = {
    SplashScreen: 'SplashScreen',
    RoleSelectorScreen: 'RoleSelectorScreen',
    LoginScreen: 'LoginScreen',
    ForgotPasswordScreen: 'ForgetPassword',
    DashBoardScreen: 'BottomTab',
    NurseryProfileScreen: 'NurseryProfile',
    Notificationss: 'Notifications',
    ContactUs: 'ContactUs',
    AddRoom: 'AddRoom',
    RoomScreen: 'RoomScreen',
    TeacherInfo: 'TeacherInfo',
    Teachers: 'Teachers',
    AddTeacher: 'AddTeacher',
    ToddlerInfo: 'ToddlerInfo',
    ToddlerScreen: 'ToddlerScreen',
    HomeScreen: 'HomeScreen',
    Teacher: 'Teacher',
    Toddler:"Toddler",
    AddToddler:"AddToddler",
    Announcement:"Announcement",
    CreateAnnouncement:"CreateAnnouncement",
    Logout: 'Logout',
    ActivityInfo:"ActivityInfo",
    ParentHomeScreen: 'ParentHomeScreen',
    TodayActivity: 'Activity',
    HealthRecordScreen:"HealthRecordScreen",
    CreateHealthRecord:'CreateHealthRecord',
    ParentProfile:"ParentProfile",
    Rating:"Rating",
    TeacherDashboard: 'TeacherDashboard',
    TeacherToddlerInfo: 'TeacherToddlerInfo',
    FAQsScreen: 'FAQsScreen',
    TeacherProfile: 'TeacherProfile',
    ParentAnnouncement:"ParentAnnouncement",
    EditToddlerProfile:"EditToddlerProfile",
    OtpScreen:"OtpScreen",
    Message:"Message",
    CreateHealthRecord:"CreateHealthRecord",
    Announcement: 'Announcement',

 AnnouncementNursery: 'AnnouncementNursery',
    ViewDocument:'ViewDocument',
    TeacherMessageScreen: 'TeacherMessageScreen',
    AssessmentDashboardScreen: 'AssessmentDashboardScreen',
    QuarterAssessment: 'QuarterAssessment',
    AsessmentScreen: 'AsessmentScreen',
    ViewAssessment: 'ViewAssessment',
    ViewQuarterAssessment: 'ViewQuarterAssessment',
    RoomDetails:"RoomDetails",
    ViewAnnouncement:"ViewAnnouncement",
    ActivityScreen: 'ActivityScreen',
    ActivityList: "ActivityList",
}
